name:                session-types
version:             0.1.0.0
github:              "MatrixAI/Architect/ProtocolResearch/SessionTypesDemo"
license:             Apache-2.0
author:              "Oliver Scarlet"
maintainer:          "oliver.scarlet@matrix.ai"
copyright:           "(c) Matrix AI 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/MatrixAI/Architect/ProtocolResearch/SessionTypesDemo#readme>

dependencies:
- base >= 4.7 && < 5
- containers # Data.Map

library:
  source-dirs: src

# executables:
#   SessionTypesDemo-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - session-types

tests:
  SessionTypesDemo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - session-types
    - hspec
    - QuickCheck
