name:                architect-compiler
version:             0.1.0.0
github:              "MatrixAI/Haskell-Demo"
license:             Apache
author:              "CMCDragonkai"
maintainer:          "roger.qiu@matrix.ai"
copyright:           "Copyright: (c) 2017 Matrix AI"

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Architect.Compiler
  dependencies:
    - hint >= 0.7 && < 0.8
    - ghc >= 7.8 && < 8.4
    - ghc-paths
    - ghc-boot
    - bytestring >= 0.10 && < 0.11
    - megaparsec >= 6.3 && < 6.4
    - scientific >= 0.3 && < 0.4
    - neat-interpolation >= 0.3 && < 0.4
    - text >= 1.2 && < 1.3
    - data-fix >= 0.2 && < 0.3
    - hashable >= 1.2 && < 1.3
    - hashmap >= 1.3 && < 1.4
    - deepseq >= 1.4 && < 1.5
    - transformers >= 0.5 && < 0.6
    - deriving-compat >= 0.3.6 && < 0.4
